services:
  - type: web
    name: ajochain-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ajochain-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: BMONI_API_KEY
        sync: false
      - key: BMONI_BASE_URL
        value: "https://embedded-dev.bmoni.com"

databases:
  - name: ajochain-db
    databaseName: ajochain
    user: ajochain_admin
